### ISSUE TITLE
Pose estimation from IMU, encoder and GPS

### ISSUE THREAD

**Issue by deepakgangwar** [VISiON-IITK/tracker#10]

**Comment by blmhemu** [comment]
Got a library "NeoGPS" . It works by collecting data and find it in a hard way : go on until you find a comma convert from char to int by subtracting '0' and so on .

**Comment by blmhemu** [comment]
Problem publishing odom information from arduino to ros.Loosing sync(may be due to large data being sent). Tommorow : run the code in ros itself and publish encoder info from arduino:: by hemanth and hardik

**Comment by deepakgangwar** [comment]
Pose estimation from encoders and IMU has been done. We will now include GPS in it.

**Comment by deepakgangwar** [comment]
Mapping has been completed using gmapping and robot_pose_ekf.
# ToDo:
* add gps to robot_pose_ekf
* try robot_localisation ros package
