### ISSUE TITLE
Gazebo

### ISSUE THREAD

**Issue by ashishkpatel** [VISiON-IITK/tracker#13]
documentation of bot using gazebo

**Comment by ashishkpatel** [comment]
making some changes in package to operate it using keyboad

**Comment by lakshayg** [comment]
Saying "some changes" is generally not a good idea and defeats the purpose
of an issue/progress tracker. Please update the comment with details.

**Comment by ashishkpatel** [comment]
`
`
![default_gzclient_camera 0 -2017-01-19t22_21_19 663754](https://cloud.githubusercontent.com/assets/24418016/22117894/b3c9c79e-de9b-11e6-8c69-def77b9b4f66.jpg)

the world file with barrels and construction cones as obstacles. bot can enter into the field from left side and can move by detecting obstacles.
 
`
`
