### ISSUE TITLE
Waypoint Navigation

### ISSUE THREAD

**Issue by ashishbhatti** [VISiON-IITK/tracker#14]
We were able to extract coordinates from GPS and using that I attempted a test run today. We are using the GPS inbuilt magnetometer as compass. But the magnetometer data is very inaccurate. We are planning to augment our system with magnetometer from other sensors like IMU.

**Comment by hardikmaheshwari** [comment]
Tried plotting data extracted from GPS on local map using rviz. Currently not able to plot correct data facing some issues. Searching the issues to plot the data on map

**Comment by deepakgangwar** [comment]
Way point navigation using encoders has been completed for firebird.
Bot can go to the next waypoint with a certain minimum velocity. The final code is present in the Control repo.
