### ISSUE TITLE
Create Occupancy Grid Maps

### ISSUE THREAD

**Issue by harshsinh** [VISiON-IITK/tracker#18]
Create occupancy grid maps based on 2D odometry data, IMU data, and Laser scan.

**Comment by deepakgangwar** [comment]
Occupancy grid based global map has been done using slam_gmapping. [video](https://teamroboconiitk.slack.com/files/dgangwar/F3UB8C9L2/screencast_2017-01-20_22_02_50.mp4) and [rosbag](https://teamroboconiitk.slack.com/files/animesh/F3VBM35QW/2017-01-21-23-16-00.bag) are available in general channel of slack.
