### ISSUE TITLE
Write drivers for Encoders

### ISSUE THREAD

**Issue by lakshayg** [VISiON-IITK/tracker#3]

**Comment by Swatigupta1997** [comment]
The encoder drivers for all available robots ( i.e. Hercules-greenbot, combat-robotics, nex-firebirdVI) in ros are uploaded on the gitlab repository-resources and controls.
1) Hercules: Custom built and working in resources repo.(greenbot)
2) combat: (contact shakya) 
3) nex-firebird: custom built using cpp library in ros- controls repo, (firebirdVI)
                        Provided with the robot: resources repo: (ros0xrobot)
