### ISSUE TITLE
Lane detection

### ISSUE THREAD

**Issue by lakshayg** [VISiON-IITK/tracker#6]

**Comment by shubhgup** [comment]
HSV threshold extraction followed by morphological opening and erosion. Perspective correction and Hough line formation on resultant image. Discrimination of right and left lane lines by lane midpoint position with respect to screen center. Labelling and grouping of lines on same lane to form single bestfit lane lines. removal of non traversable region based on lanes

Shortcomings : misses lines due to poor lighting. Line labelling algorithm too primitive, resulting in incorrect left-right assignment especially on lines with near horizontal slopes. Also doesnt work well with ramp and fences. Obstacle removal not implemented in this

**Comment by shubhgup** [comment]
![screenshot from 2017-01-08 23 25 57](https://cloud.githubusercontent.com/assets/22560448/21752172/de531538-d5f9-11e6-88d4-62f8625f83cd.png)
![screenshot from 2017-01-08 23 25 07](https://cloud.githubusercontent.com/assets/22560448/21752174/e20e2208-d5f9-11e6-8cd6-ec573bee1809.png)
![screenshot from 2017-01-08 23 24 59](https://cloud.githubusercontent.com/assets/22560448/21752178/f0807b88-d5f9-11e6-88f0-445ce14862b5.png)





![screenshot from 2017-01-08 22 45 17](https://cloud.githubusercontent.com/assets/22560448/21752024/0960ed16-d5f7-11e6-8ca9-47810f1763d6.png)
![screenshot from 2017-01-08 22 45 49](https://cloud.githubusercontent.com/assets/22560448/21752025/097b3086-d5f7-11e6-9c0d-7715df4cf207.png)

**Comment by AnayMehrotra** [comment]
![screen shot 2017-01-09 at 11 12 59 pm](https://cloud.githubusercontent.com/assets/23269594/21777005/06902012-d6c3-11e6-9a00-81c958efdcde.png)
![screen shot 2017-01-09 at 11 25 20 pm](https://cloud.githubusercontent.com/assets/23269594/21777004/068f45c0-d6c3-11e6-9f58-1abeb898737e.png)
![screen shot 2017-01-09 at 11 25 36 pm](https://cloud.githubusercontent.com/assets/23269594/21777007/0698f926-d6c3-11e6-8b95-c243fa337efb.png)

Detecting lanes using splins. 
Techniques 

1. Obstacle Removal : Done using HSV thresholding.
2. Region of Interest : A custom (variable) kernel is convoluted on the image. Regions of interest have high values. Kernel used contains ones as wide as the lane and an equal number of negative ones distributed on either side, i.e. for lane of width four kernel is [-1 -1 1 1 1 1 -1 -1]
3. Spline Making : 

- 25 interest points are chosen from either side of the image. These are used to extend splines to a region at a (specified) distance from them. 
- Splines are rated on basis of their average distance from points of interest, which are then extended further.
- Longer splines are promoted, ensuring a lane is not missed.

4. Averaging : The average of 10 frames is taken at a time. This reduces fluctuations and propagates information through frames.
5. Top view : Using warp perspective transform.


Shortcomings :

- Averaging ignores bot's motion and confidence (probability) in splines. This results in a laggy responce.

**Comment by priteshkumbhare** [comment]
Detecting Grids where lane is present
Techniques
1. Divided into Grids 20x36.
2. Mean and Std. Deviation of pixel value of 2xBLUE-GREEN of each grid.
3. Applied Threshold of Mean + Std. Deviation. The one with higher is more probable to be part of lane (and least probable to be a grass ONLY).
