### ISSUE TITLE
Motion Planning Within Lane

### ISSUE THREAD

**Issue by aalapshah12297** [VISiON-IITK/tracker#9]

**Comment by aalapshah12297** [comment]
![output 11-01-17](https://cloud.githubusercontent.com/assets/24418184/21820483/d718d814-d795-11e6-963e-c26521d0a1d8.png)
Motion plainning for non-holonomic robot using RRT
Blue nodes represent the full RRT generated
Red nodes represent the chosen path to goal (co-ordinates supplied)

**Comment by aalapshah12297** [comment]
Will implement incremental RRT-based non-holonomic planning within dynamic local map with Lidar-like obstacle map. Will then try to use space-partitioning or some other geometric method to reduce time complexity of nearest-neighbour search while generating RRT.

**Comment by aalapshah12297** [comment]
13/01/17
[output (with tree shown).zip](https://github.com/igvc-iitk/tracker/files/706153/output.with.tree.shown.zip)
Implemented incremental RRT-based non-holonomic planning within dynamic local map with Lidar-like obstacle map. Tuned RRT parameters (node generation limit, max edge length, etc.) till fast and reliable results were generated.

**Comment by aalapshah12297** [comment]
14/01/17
Started implementing the same RRT algorithm in C++ (currently only for static maps). Currently the algorithm gives valid paths most of the times but gets stuck at other times (reason unknown - to be debugged).

**Comment by aalapshah12297** [comment]
15/01/17
![path1](https://cloud.githubusercontent.com/assets/24418184/21963036/c1ac0cdc-db58-11e6-8da9-2fa319d0608c.png)
![path2](https://cloud.githubusercontent.com/assets/24418184/21963037/c1d2ed84-db58-11e6-90ec-d40a70d10279.png)
Debugged previous code. Generated some paths on a simple square 100x100 map with a 50x50 obstacle in the center. Plotted the paths using Matlab (figures above).

**Comment by aalapshah12297** [comment]
max steering angle = 20 degree, tree size = 400 (path shown in red, tree in blue)
![output cpp 17-01-17](https://cloud.githubusercontent.com/assets/24418184/22033513/c99baa62-dd0e-11e6-9d36-6cc58939a0ab.png)
max steering angle = 30 degree, tree size = 1200 (only path shown, in red)
![output1 cpp 17-01-17](https://cloud.githubusercontent.com/assets/24418184/22033920/7ce6b976-dd10-11e6-8044-318c854dddff.png)

Completed porting of previous MATLAB script to C++. Generated some paths on the same map as before and wrote a MATLAB script to plot the output. Currently creating a ROS node using the C++ code.

**Comment by aalapshah12297** [comment]
Implemented potential field based correction factor to reduce jaggedness of path generated by RRT (only slightly)
Some Examples: (Blue = original path, Red = corrected path)
1. 
![1 - rrt](https://cloud.githubusercontent.com/assets/24418184/22076504/58f773e0-ddd6-11e6-928c-618d1ff9b2eb.png)
![1 - rrt with potential](https://cloud.githubusercontent.com/assets/24418184/22076505/590436a2-ddd6-11e6-9a9a-f7571a6ddf13.png)

2.
![2 - rrt](https://cloud.githubusercontent.com/assets/24418184/22076513/64b0a954-ddd6-11e6-92f4-7c5142036c0e.png)
![2 - rrt with potential](https://cloud.githubusercontent.com/assets/24418184/22076514/64b560c0-ddd6-11e6-8e02-fcd68e265a71.png)

**Comment by bhuvig** [comment]
ROS node of RRT up and running. Currently works on a hard coded map while subscribing to start and end coordinates. Publishes path on a topic.
